[package]
name = "normp/code-test"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "ruizukun-dev/janitor@1.14.7"
TestEZ = "roblox/testez@0.4.1"